# Generated by Django 5.0.6 on 2024-06-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('maxtemp_c', models.FloatField()),
                ('mintemp_c', models.FloatField()),
            ],
            options={
                'unique_together': {('city', 'date')},
            },
        ),
    ]
