# Generated by Django 5.0.6 on 2024-06-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usersearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearch',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
